# Generated by Django 4.2.1 on 2023-05-30 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('employeeid', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('current_salary', models.CharField(max_length=30)),
                ('expected_salary', models.CharField(max_length=30)),
                ('current_domain', models.CharField(max_length=100)),
                ('change_domain', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('password1', models.CharField(max_length=40)),
            ],
        ),
    ]
